// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFE9IcwZWNu6pUX1S7jI3P3nyVhvyevB0',
    appId: '1:669782400052:android:6e6ba3fddf543cb54efe61',
    messagingSenderId: '669782400052',
    projectId: 'remindall-2535c',
    storageBucket: 'remindall-2535c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFpg5EaFKkC6-rru74iUkZKuy2K-4KvhQ',
    appId: '1:669782400052:ios:5d95f552c93a0b074efe61',
    messagingSenderId: '669782400052',
    projectId: 'remindall-2535c',
    storageBucket: 'remindall-2535c.appspot.com',
    androidClientId: '669782400052-ipvmid156ppcqjjtmemh3pvpg30elq9r.apps.googleusercontent.com',
    iosClientId: '669782400052-72940ts3kk6hdpu9d889v9agt5kivb98.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp3',
  );

}